using System.Collections;
using System.Collections.Generic;
using UnityEngine;
/*
Permite que el SmallMonster detecte si choc칩 con una pared
Autor: Erick Hern치ndez Silva
*/
public class SmallMonsterChoque : MonoBehaviour
{
    //Variable publica est치tica que permite saber al small monster si choc칩 con pared
    public static bool SmallMonsterChoco;
    private void OnTriggerEnter2D(Collider2D other) {
        if(other.CompareTag("Mapa")){
            SmallMonsterChoco = true;
        }
    }
    private void OnTriggerExit2D(Collider2D other) {
        if(other.CompareTag("Mapa")){
            SmallMonsterChoco = false;
        }
    }
}
